FROM debian:latest

MAINTAINER Felix Song sigmafelix@hotmail.com

ENV DEBIAN_FRONTEND noninteractive
ENV CRAN_URL https://cloud.r-project.org/

ADD https://s3.amazonaws.com/rstudio-server/current.ver /tmp/ver

RUN set -e \
      && ln -sf /bin/bash /bin/sh

RUN set -e \
      && apt-get -y update \
      && apt-get -y install --no-install-recommends --no-install-suggests \
        apt-transport-https apt-utils ca-certificates gnupg \
      && apt-get -y dist-upgrade \
      --no-install-recommends --no-install-suggests \
        curl libapparmor1 libclang-dev libedit2 libssl-dev libssl1.1 lsb-release \
        psmisc sudo \
        #r-base \#
      && apt-get -y install --no-install-recommends --no-install-suggests \
        apt-transport-https apt-utils ca-certificates gnupg \
      && sudo sh -c 'echo "deb https://cloud.r-project.org/bin/linux/debian buster-cran40/" >> /etc/apt/sources.list' \
      && apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF' \
      && apt-get -y update \
      && apt-get -y autoremove \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

RUN  set -e \
      && apt-get -y update \
      && apt-get -y install --no-install-recommends --no-install-suggests \
        nano libgdal-dev libgeos-dev libproj-dev libudunits2-dev libspatialindex-dev\
		libcairo2-dev build-essential gcc gfortran libopenblas-dev libatlas3-base libmagick++-dev libgl-dev \
		libprotobuf-dev libv8-dev libjq-dev default-jre default-jdk \
      && apt-get -y install r-base r-base-dev \ 
      && apt-get -y autoremove \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

RUN  set -e \
      && apt-get -y update \
      && apt-get -y install --no-install-recommends --no-install-suggests \
		 jags \
	  && apt-get -y autoremove \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

RUN set -e \
      && ln -s /dev/stdout /var/log/syslog \
      && curl -S -o /tmp/rstudio.deb \
        https://download2.rstudio.org/server/bionic/amd64/rstudio-server-$(cut -f 1 -d - /tmp/ver)-amd64.deb \
      && apt-get -y install /tmp/rstudio.deb \
      && rm -rf /tmp/rstudio.deb /tmp/ver

RUN set -e \
      && useradd -m -d /home/rstudio -g rstudio-server rstudio \
      && echo rstudio:rstudio | chpasswd \
      && echo "r-cran-repos=${CRAN_URL}" >> /etc/rstudio/rsession.conf

RUN set -e \
	  && Rscript -e "install.packages('pacman')" \
	  #&& Rscript -e "library(pacman);p_load(char = c('sf', 'sp', 'spdep', 'raster', 'terra', 'geofacet', 'gstat', 'automap', 'tmap', 'dplyr', 'plyr', 'tidyr', 'magrittr', 'lubridate', 'xtable', 'tidyverse', 'mice', 'caret', 'caretEnsemble', 'rjags', 'spBayes', 'stars', 'doParallel', 'foreach', 'doSNOW', 'future', 'mlr', 'missForest', 'mlrCPO', 'fuzzyjoin', 'ggpmisc', 'ggthemes', 'BiocManager'))" \#
	  && Rscript -e ".libPaths(c('/home/rstudio/R/x86_64-pc-linux-gnu-library/4.0', .libPaths()));library(pacman);p_load(future.apply, fuzzyjoin, mlrCPO, sf, automap, gstat, geofacet, tidyverse, foreach, caretEnsemble, stars, rjags, ggpmisc, ggthemes, BiocManager);install.packages('INLA', repos=c(getOption('repos'), INLA='https://inla.r-inla-download.org/R/stable'), dep=TRUE, Ncpus = 8, INSTALL_opts = c('--no-lock'))"


	  
EXPOSE 8788

ENTRYPOINT ["/usr/lib/rstudio-server/bin/rserver"]
CMD ["--server-daemonize=0", "--server-app-armor-enabled=0"]
